name: Pylint Workflow

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Python version'
        required: false
        default: '3.10'
        type: string

jobs:
  pylint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version  }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Analysing the code with pylint
        id: pylint
        continue-on-error: true
        run: |
          pylint $(git ls-files '*.py')

      # - name: Upload analysis results to GitHub
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: pylint-results.sarif
      #     wait-for-processing: true
      #     category: Linting
