name: Pytest Workflow

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Python version'
        required: false
        default: '3.10'
        type: string
      extra_args:
        description: 'CLI Arguments to be passed to pytest command'
        required: false
        default: '--cov=src -vv'
        type: string

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Running Python unit tests
        id: pytest
        continue-on-error: true
        run: |
          pytest ${{ inputs.extra_args }}

      # - name: Upload test results to GitHub
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: pytest-results.sarif
      #     wait-for-processing: true
      #     category: Testing
